sudo: required
services: 
  - docker

language : node_js

node_js:
  - '6'

env:
  COMPOSE_VERSION: 1.11.2

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - mocha
  - docker-compose build

notifications:
  email:
    recipients:
      - omrumbakitemiz@outlook.com

deploy:
  provider: heroku
  api_key:
    secure: 56f062a2-242a-4f2d-9eb9-dc0e440ac099
  on:
    all_branches: true